### ISSUE TITLE
Cookie is not encrypt in test case, CookieHtmlTest, should test in browser

### ISSUE THREAD

**Issue by cftdanny** [cftdanny/corona.old#80]
涓ラ噸: Fail to decode cookie, just skip this exception
java.io.IOException: Bad Base64 input character decimal 123 in array position 0
    at com.corona.util.Base64.decode(Base64.java:1205)
    at com.corona.util.Base64.decode(Base64.java:1260)
    at com.corona.util.Base64.decode(Base64.java:1228)
    at com.corona.servlet.util.CookieManagerImpl.decrypt(CookieManagerImpl.java:206)
    at com.corona.servlet.util.CookieManagerImpl.getCookie(CookieManagerImpl.java:239)
    at com.corona.servlet.util.CookieManagerImpl.getValue(CookieManagerImpl.java:223)
    at com.corona.servlet.injecting.cookieparam.CookieParamInjectParameter.get(CookieParamInjectParameter.java:69)
    at com.corona.context.AbstractInjectMethod.invoke(AbstractInjectMethod.java:104)
    at com.corona.servlet.handling.producer.ProducerHandler.handle(ProducerHandler.java:150)
    at com.corona.servlet.Handlers.handle(Handlers.java:87)
    at com.corona.servlet.ApplicationServlet.service(ApplicationServlet.java:102)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:538)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:662)

**Comment by cftdanny** [comment]
Should be URL problem
